export const RECEIVE_USERS_EXCHANGES = 'RECEIVE_USERS_EXCHANGES';
export const RECEIVE_SINGLE_EXCHANGE = 'RECEIVE_SINGLE_EXCHANGE';
export const CREATE_EXCHANGE = 'CREATE_EXCHANGE';
export const ADD_PERSON_TO_EXCHANGE = 'ADD_PERSON_TO_EXCHANGE';
export const REMOVE_PERSON_FROM_EXCHANGE = 'REMOVE_PERSON_FROM_EXCHANGE';
export const RESTRICT_PERSON = 'RESTRICT_PERSON';
export const MAKE_LIST = 'MAKE_LIST';

export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_SINGLE_USER = 'RECEIVE_SINGLE_USER';
